Fix wording and puncutation of settings descriptions.
gorilla-devs/GDLauncher pull request #1080
Opened 2021-09-25 00:10 UTC by huantianad

## Purpose
Settings menu descriptions were inconsistently punctuated, as well as awkwardly worded.

## Approach
Add periods to ends of all sentences, as well as reword slightly.

#### Open Questions and Pre-Merge TODOs
- [ ] Is "select" the correct word for game resolution, JVM memory, and JVM args?

2021-09-25 06:41 UTC, Code-Ac requested changes
All around a good pr, would definitely approve it if there weren't this little one.

2021-09-25 06:41 UTC, Code-Ac commented on src/common/modals/Settings/components/General.js
> +          connection, select at max 3.
I would prefer `at most` here

2021-09-25 17:35 UTC, huantianad commented on src/common/modals/Settings/components/General.js
> +          connection, select at max 3.
Changed!

2021-09-25 17:36 UTC, huantianad commented on src/common/modals/Settings/components/General.js
> +          ALL instance data.
Also changed up the wording here, not sure if there's a better way to word this

2021-09-25 17:43 UTC, Code-Ac approved these changes

2021-09-25 17:44 UTC, Code-Ac approved these changes
Oh didn’t know this feature existed on GH
But yes the changes are approved by myself. Good Idea to do that.

2021-10-01 10:29 UTC, killpowa approved these changes

2021-10-01 10:29 UTC, merged