GDLib refactor MVP
gorilla-devs/GDLauncher pull request #1213
Opened 2021-12-15 22:31 UTC by killpowa

hi

2021-12-18 14:32 UTC, fulviodenza approved these changes

2021-12-18 15:52 UTC, fulviodenza approved these changes
LGTM

2021-12-19 01:09 UTC, Kaliendo commented
LGTM

2021-12-19 01:32 UTC, Kaliendo approved these changes
LGTM!

2021-12-19 08:34 UTC, Code-Ac requested changes

2021-12-19 08:34 UTC, Eskaan commented on README.md
>  - C++ compiler (g++ or windows build tools)
Add Go 17 here.
Also what things here do we even need anymore?

2021-12-19 08:34 UTC, Eskaan commented on gdlib/FSWatcher.go
> +	}
Just move it into the loop.
(You said you fixed it already, just resolve when deploying)

2021-12-19 08:34 UTC, Eskaan commented on gdlib/FSWatcher.go
> +				}
What exactly needs to be fixed here? Does it fail when there is no read permission on the directory?

2021-12-19 08:34 UTC, Eskaan commented on gdlib/adapters/socket.go
> +const PORT = 7890
Will this port be running open to the local network in the future? If yes, we should see that we only accept requests from localhost

2021-12-19 08:34 UTC, Eskaan commented on gdlib/adapters/socket.go
> +			quitError <- errors.New("quitting caused by no ping received within 10s from startup")
Little typo, just capitalise and set a dot.

2021-12-19 08:34 UTC, Eskaan commented on gdlib/adapters/socket.go
> +const PORT = 7890
nvm I think you are doing that in line 98, resolve it when I am right

2021-12-19 08:34 UTC, Code-Ac commented on gdlib/adapters/socket.go
> +	}
Error says its the path, change that to action

2021-12-19 08:34 UTC, Code-Ac commented on gdlib/adapters/socket.go
> +		fmt.Println("FSWatcher: List")
// Todo add listing feature?

2022-01-08 23:49 UTC, fulviodenza approved these changes

2022-06-04 16:35 UTC, closed without merging