globalJavaArguments
gorilla-devs/GDLauncher pull request #169
Opened 2019-03-14 15:16 UTC by Ladvace

2019-03-14 15:52 UTC, gorilla-devs commented on app/actions/settings.js
> +export const SET_GLOBAL_ARGUMENTS = 'SET_GLOBAL_ARGUMENTS';
change to SET_GLOBAL_JAVA_ARGUMENTS

2019-03-14 15:52 UTC, gorilla-devs commented on app/actions/instancesManager.js
> +    console.log("JAVA-ARGS", settings.Jarguments);
use camel-case

2019-03-14 15:52 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        <Card style={{ marginTop: 15, maxHeight: 150 }} title="Override global java arguments">
use pascal-case for titles

2019-03-14 15:52 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.scss
> +.JavaArginput {
use camel-case

2019-03-14 15:53 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +function javaArguments(props) {
components names should be pascal-case

2019-03-14 15:54 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +  let defaultARGS = `-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true ${dosName}${
use camel-case for variables.
Avoid let when using constants

2019-03-14 15:55 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +  const [globalArg, setGlobalArg] = useState();
Always set a default value on useState

2019-03-14 15:55 UTC, blarfoon commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      const StorejavaArgumentsSec = store.get('settings.java.javaArg');
use camel-case for variables

2019-03-14 15:56 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      props.arg(StorejavaArgumentsSec);
use camel-case

2019-03-14 15:56 UTC, blarfoon commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      setGlobalArg(StorejavaArgumentsSec);
use camel-case

2019-03-14 15:56 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      const StorejavaArguments = store.set('settings.java.javaArg', defaultARGS);
use camel-case

2019-03-14 15:56 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      const readStorejavaArguments = store.get('settings.java.javaArg');
use camel-case

2019-03-14 15:57 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    const StorejavaArguments = store.set('settings.java.javaArg', defaultARGS);
use camel-case

2019-03-14 15:58 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +          <Button type="primary" onClick={() => reset()}>reset</Button>
use pascal case for button texts

2019-03-14 15:58 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +)(javaArguments);
components names should be pascal-cased

2019-03-14 15:59 UTC, gorilla-devs commented on app/utils/MCLaunchCommand.js
> +import javaArg from '../components/Settings/components/JavaManager/JavaArguments';
Do not import components in utility functions

2019-03-14 16:00 UTC, blarfoon requested changes
See code comments

2019-03-14 16:11 UTC, gorilla-devs commented on app/actions/settings.js
> +export function arg(args) {
Change function name: too generic

2019-03-14 16:11 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +              <Button type="primary" >reset</Button>
Button texts should be pascal-cased

2019-03-14 16:12 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +import { arg } from '../../../../actions/settings';
same as above (too generic)

2019-03-14 16:13 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      setGlobalArg(readstoreJavaArguments);
variables names should be camel-cased

2019-03-14 16:13 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      const readstoreJavaArguments = store.get('settings.java.javaArg');
variables names should be camel-cased

2019-03-14 16:13 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +      props.arg(readstoreJavaArguments);
variables names should be camel-cased

2019-03-14 16:13 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    props.arg(globalArg);
Same as above (name too generic)

2019-03-14 16:14 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    const readstoreJavaArguments = store.get('settings.java.javaArg');
variables should be camel-case

2019-03-14 16:14 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    props.arg(readstoreJavaArguments);
Same as above (name too generic)

2019-03-14 16:20 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +              <Button type="primary" >reset</Button>
Reset should be pascal-case

2019-03-15 11:52 UTC, gorilla-devs commented on app/actions/instancesManager.js
> +      settings.java.javaArg
use args instead of arg

2019-03-15 11:53 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.scss
> +.javaArginput {
css classes should be camel-cased

2019-03-15 11:53 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +  const [globalArgs, setglobalArgssInput] = useState(null);
how many s are in this word lol "setglobalArgssInput"

2019-03-15 11:55 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    const storeJavaArgumentsSec = store.get('settings.java.javaArg');
What's sec?

2019-03-15 11:55 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    readStoreJavaArg();
use args instead of arg

2019-03-15 11:56 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +    } else message.error("enter valid arguments");
use pascal-case for messages

2019-03-15 11:56 UTC, gorilla-devs commented on app/components/Settings/components/JavaManager/JavaArguments.js
> +        }} onChange={(e) => setglobalArgssInput(e.target.value)} />
same as above (setglobalArgssInput)

2019-03-15 11:57 UTC, gorilla-devs commented on app/reducers/settings.js
> +    javaArg: DEFAULT_ARGS
use args instead of arg

2019-03-15 11:57 UTC, gorilla-devs commented on app/reducers/settings.js
> +        javaArg: action.payload
same as above

2019-03-15 11:58 UTC, gorilla-devs commented on app/reducers/settings.js
> +        javaArg: action.payload
same as above

2019-03-15 11:58 UTC, blarfoon requested changes
See comments

2019-03-15 12:09 UTC, gorilla-devs commented on app/actions/settings.js
> +          javaArg: DEFAULT_ARGS
use args instead of arg

2019-03-15 15:33 UTC, blarfoon approved these changes

2019-03-15 15:34 UTC, merged