overrideJavaArguments
gorilla-devs/GDLauncher pull request #175
Opened 2019-03-24 06:48 UTC by Ladvace

2019-03-24 19:38 UTC, gorilla-devs commented on app/actions/downloadManager.js
> +        overrideMemory: 3096
By default none of those should be present. Only when an override is set it is added. If no override is set, it is simply not present and the global is used instead

2019-03-24 19:40 UTC, gorilla-devs commented on app/actions/instancesManager.js
> +      config.overrideMemory === ''
it should be`config.overrideMemory === undefined` since when no override is set, it is simply not present

2019-03-24 19:40 UTC, gorilla-devs commented on app/actions/serverManager.js
> +import { message } from 'antd';
Why is serverManager in this PR?

2019-03-24 19:42 UTC, gorilla-devs commented on app/components/Common/WindowNavigation/components/HorizontalMenu/HorizontalMenu.js
> +            className={styles.a}
Why is this in this PR?

2019-03-24 19:46 UTC, gorilla-devs commented on app/components/ServerCreatorModal/ServerCreatorModal.js
> +import styles from './ServerCreatorModal.scss';
Why is this file in this PR?

2019-03-24 19:46 UTC, gorilla-devs commented on app/components/ServerCreatorModal/ServerCreatorModal.scss
> +
Why is this file in this PR?

2019-03-24 19:47 UTC, gorilla-devs commented on app/components/ServerManager/ServerManager.js
> +import psTree from 'ps-tree';
Why is this file in this PR?

2019-03-24 19:48 UTC, gorilla-devs commented on app/components/ServerManager/ServerManager.scss
> +.serverSettings{
Why is this file in this PR?

2019-03-24 19:48 UTC, gorilla-devs commented on app/components/ServerManager/command.js
> +function Command(props) {
Why is this file in this PR?

2019-03-24 19:49 UTC, gorilla-devs commented on app/components/ServerManager/serverCommand.js
> +import Command from './command';
Why is this file in this PR?

2019-03-24 19:49 UTC, gorilla-devs commented on app/components/serverCommandsModal/serverCommandsModal.js
> +import path from 'path';
Why is this file in this PR?

2019-03-24 19:49 UTC, gorilla-devs commented on app/components/serverCommandsModal/serverCommandsModal.scss
> +  overflow-y: auto;
Why is this file in this PR?

2019-03-24 19:50 UTC, gorilla-devs commented on app/reducers/serverManager.js
> +        ...state,
Why is this file in this PR?

2019-03-24 19:50 UTC, gorilla-devs commented on package.json
> +    "@rauschma/stringio": "^1.4.0",
Remove this line since is not needed

2019-03-25 10:26 UTC, gorilla-devs commented on app/actions/downloadManager.js
> +import { DEFAULT_ARGS } from '../constants';
Why importing an unused variable?

2019-03-25 10:27 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +function javaMemorySlider(props) {
components names should be pascal-case

2019-03-25 10:28 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +      if (config.overrideMemory === undefined && e === true) {
e === true is equal to e

2019-03-25 10:28 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +      } else if (config.overrideMemory !== undefined && e === false) {
e === true is equal to e

2019-03-25 10:32 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +    config.overrideArgs = DEFAULT_ARGS;
Useless assignment

2019-03-25 10:35 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +    const modifiedConfig = JSON.stringify(config);
use
`JSON.stringify({
...config,
overrideArgs: DEFAULT_ARGS
})`

2019-03-25 10:40 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +      config.overrideArgs = overrideArgs;
Try not to mutate objects when possible 🥇

2019-03-25 10:40 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +      const modifiedConfig = JSON.stringify(config);
JSON.stringify({ ...config, overrideArgs: DEFAULT_ARGS })

2019-03-25 10:41 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +  async function configManagment() {
configManagement please

2019-03-25 10:42 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +    if (configFile.overrideArgs !== undefined) {
You can safely remove !== undefined

2019-03-25 10:42 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +    configManagment();
management <------------

2019-03-25 10:44 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +  const submit = async () => {
Use a more specific name for this function

2019-03-25 10:44 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +  const reset = async () => {
Use a more specific name for this function

2019-03-25 10:45 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +      if (config.overrideArgs === undefined && e === true) {
I think you can remove both ===

2019-03-25 10:45 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        config.overrideArgs = props.overrideJavaArgs;
Same as above

2019-03-25 10:45 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        const modifiedConfig = JSON.stringify(config);
Same as above

2019-03-25 10:48 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +      } else if (config.overrideArgs !== undefined && e === false) {
You can remove both ===

2019-03-25 10:48 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        config.overrideArgs = undefined;
Same as above

2019-03-25 10:48 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        const modifiedConfig = JSON.stringify(config);
Same as above

2019-03-25 10:50 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +              {switchState ? javaArgInput : <div />}
Return null instead of an empty div. Decreses overall complexity

2019-03-25 10:52 UTC, gorilla-devs commented on app/reducers/settings.js
> +    overrideJavaArgs: DEFAULT_ARGS
Imho this is completely useless and you can get rid of it

2019-03-25 10:53 UTC, gorilla-devs commented on app/utils/MCLaunchCommand.js
> +  // const ramMemory = config.overrieMemory === '' ? ram : config.overrieMemory;
???????

2019-03-25 10:54 UTC, gorilla-devs commented on app/utils/MCLaunchCommand.js
> +"${javaPath}" ${(config.overrideArgs === undefined
You can use `config.overrideArgs ? config.overrideArgs : javaArguments

2019-03-25 10:55 UTC, gorilla-devs commented on yarn.lock
> +"@rauschma/stringio@^1.4.0":
I would appreciate if you could remove this file from the PR. Thanks

2019-03-25 10:55 UTC, blarfoon requested changes
See comments

2019-03-25 12:03 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +    if (configFile.overrideMemory !== undefined) {
This can be written as `if(config.overrideMemory)`

2019-03-25 12:04 UTC, gorilla-devs commented on app/actions/instancesManager.js
> +      config.overrideMemory === undefined
This can be written as
`config.overrideMemory ? config.overrideMemory : settings.java.memory`

2019-03-25 12:05 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +        config.overrideMemory = props.overrideMemory;
Try not to mutate objects

2019-03-25 12:05 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +        delete config.overrideMemory;
Try not to mutate objects

2019-03-25 12:06 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/JavaMemorySlider.js
> +      {switchState ? memorySlider : <div />}
Don't return empty divs, return null instead

2019-03-25 12:08 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        config.overrideArgs = props.overrideJavaArgs;
This is not fixed

2019-03-25 12:09 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +        config.overrideArgs = undefined;
Try not to mutate objects

2019-03-25 12:20 UTC, gorilla-devs commented on app/reducers/settings.js
> +    overrideMemory: 3096,
If I change the override memory for one instance, it changes it for all the instances

2019-03-25 12:20 UTC, blarfoon requested changes
See comments and fix bugs

2019-03-31 15:06 UTC, gorilla-devs commented on app/actions/instancesManager.js
> +      config.overrideMemory ? config.overrideMemory : settings.java.memory,
Write `config.overrideMemory || settings.java.memory` instead

2019-03-31 15:13 UTC, gorilla-devs commented on app/reducers/settings.js
> +  SET_GLOBAL_JAVA_ARGUMENTS,
What is this used for?

2019-03-31 15:14 UTC, gorilla-devs commented on app/routes.js
> -)(RouteDef);
Don't remove newline at the end of the file

2019-03-31 15:14 UTC, gorilla-devs commented on app/utils/MCLaunchCommand.js
> +"${javaPath}" ${(config.overrideArgs
Can write `config.overrideArgs || javaArguments` instead

2019-03-31 15:15 UTC, gorilla-devs commented on yarn.lock
> +"@sinonjs/commons@^1", "@sinonjs/commons@^1.3.1":
Don't include yarn.lock to the PR

2019-03-31 15:15 UTC, gorilla-devs commented on app/components/InstanceManagerModal/Settings/Settings.js
> +    } else message.error('Enter Valid Arguments');
Don't use pascal case for messages

2019-04-08 18:49 UTC, closed without merging