New Settings
gorilla-devs/GDLauncher pull request #312
Opened 2020-02-04 18:15 UTC by Ladvace

NewSettings

2020-02-04 18:25 UTC, killpowa commented on src/common/modals/Settings/components/Instances.js
> +import { remote } from "electron";
Do not use the `remote` module, use `ipcRenderer.invoke` instead

2020-02-04 18:25 UTC, killpowa commented on src/common/modals/Settings/components/Instances.js
>      await fsa.emptyDir(path.join(InstancesPath, "versions"));
These are not necessary

2020-02-04 18:25 UTC, killpowa commented on src/common/modals/Settings/components/Instances.js
> +  remote.dialog.showOpenDialog(
use `ipcRenderer.invoke` instead

2020-02-04 18:26 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +import { remote } from "electron";
Do not use the `remote` module

2020-02-04 18:26 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +  remote.dialog.showOpenDialog(
Do not use the `remote` module

2020-02-04 18:26 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +  16384: "16384 mb"
Please use `MB` instead of `mb`

2020-02-04 18:27 UTC, killpowa commented on src/common/modals/Settings/components/MyAccount_preferences.js
> +const { app } = require("electron").remote;
Do not use `remote`

2020-02-04 18:27 UTC, killpowa commented on src/common/modals/Settings/components/MyAccount_preferences.js
> +  const [releaseChannel, setReleaseChannel] = useState(0 ? "Release" : "Beta");
0 will always be falsy

2020-02-05 13:02 UTC, blarfoon requested changes

2020-02-05 13:02 UTC, blarfoon commented on src/common/modals/Settings/components/Instances.js
> +    updateInstancesPath
Only pass serializable data

2020-02-05 13:02 UTC, blarfoon commented on src/common/modals/Settings/components/Instances.js
> +      <H1
Why uppercase?

2020-02-05 13:02 UTC, blarfoon commented on src/common/modals/Settings/components/Instances.js
> +      </H1>
Why uppercase?

2020-02-05 13:02 UTC, blarfoon commented on src/common/modals/Settings/components/Instances.js
> +          onChange={e => setOverrideInstancesPath(e)}
Write it as `onChange={setOverrideInstancesPath}`

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +const H1 = styled.h1`
Choose another name

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +          onChange={c => setAutodetectJavaPath(c)}
Same as above

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +      </H1>
Same as above

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/Java.js
> +      <H1
Same as above

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/MyAccount_preferences.js
> +  const [releaseChannel, setReleaseChannel] = useState(releaseC);
It doesn't make sense to have a local state when you already have this data from redux

2020-02-05 13:02 UTC, killpowa commented on public/electron.js
> +ipcMain.handle("restart", () => {
Do not create duplication, `appRestart` already exists

2020-02-05 13:02 UTC, killpowa commented on src/common/modals/Settings/components/MyAccount_preferences.js
> +            onClick={() => ipcRenderer.invoke("restart")}
Do not create duplication, `appRestart` already exists

2020-02-05 13:06 UTC, Ladvace commented on src/common/modals/Settings/components/Instances.js
> +      <H1
because it's a custom tag based on the h1

2020-02-05 13:07 UTC, Ladvace commented on src/common/modals/Settings/components/Instances.js
> +      <H1
because It's a custom tag based on the h1 html tag

2020-02-05 13:45 UTC, merged