ScreenShot Manager
gorilla-devs/GDLauncher pull request #337
Opened 2020-02-27 12:06 UTC by Ladvace

2020-02-27 12:17 UTC, blarfoon requested changes

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/Notes.js
> +    const notes = JSON.parse(await fs.readFile(configPath));
Do not read config file directly. Read config data from redux instead

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/Notes.js
> +          // spellCheck
???

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/Notes.js
> +          // }}
Remove it if you don't use it

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +import { _getInstancesPath } from "../../utils/selectors";
Relative imports should come last

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  height: 100px;
height is set 2 times

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +    Promise.all(
There's no need to use promise all if you don't wait for the result

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +        });
```suggestion
        sortedScreens.sort((a, b) => a.timestamp - b.timestamp);
```

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  const clientId = "18d87e44184ea34";
Don't hardcode the clientId here

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  const res = await axios.post("https://api.imgur.com/3/image", bodyFormData, {
API calls should not happen in the component. Extract the logic

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +    console.error;
??

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +      console.log(`${filename} file Changed`);
remove this

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  if (screens.sort().join(",") === selectedScreens.sort().join(",")) {
This will fail.
```suggestion
  if (screens.slice().sort().join(",") === selectedScreens.slice().sort().join(",")) {
```

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +    }
This try catch will not work since there is no async call

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +                  &&:first-child {
It should be 
```suggestion
                  &:first-child {
```

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  &&:hover {
It should be 
```suggestion
  &:hover {
```

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  &&:hover {
It should be 
```suggestion
  &:hover {
```

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +                            );
Remove this

2020-02-27 12:17 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +              }
```suggestion
                height: 100%;
                text-align: center;
                padding-top: 25%;
```

2020-03-01 01:48 UTC, CrankySupertoon commented
hmm

2020-03-02 13:32 UTC, blarfoon requested changes

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  &&: {
???

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  && {
Rmove `&&`

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  if (!multipleOrNot) {
Instead of doing this, always pass an array, which can also contain 1 element

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +        ).birthtimeMs;
?????????????

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +        });
```suggestion
        sortedScreens.sort((a, b) => a.timestamp - b.timestamp);
```

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  const clientId = "18d87e44184ea34";
Move this to constants

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +  const res = await axios.post("https://api.imgur.com/3/image", bodyFormData, {
API calls should not happen in the component. Extract the logic

2020-03-02 13:32 UTC, killpowa commented on src/common/modals/InstanceManager/ScreenShot.js
> +        startListener(ScreenShotsDir, selectedScreens, setGroupedStortedPhoto);
The listener should be closed when the component is unmounted

2020-03-02 13:37 UTC, killpowa commented on src/common/utils/constants.js
> +export const CLIENT_ID = "18d87e44184ea34";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 13:37 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- src/common/modals/InstanceManager/Notes.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094&bid=16716777)

2020-03-02 21:10 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 21
           

Clones added
============
- src/common/modals/InstanceManager/Notes.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094&bid=16716777)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import React from "react";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import path from "path";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import Modal from "../components/Modal";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Missing file extension for "../components/Modal"](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  );
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/components/ModalsManager.js
> +import ShowScreenShot from "../modals/ShowScreenShot";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import React from "react";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Resolve error: unable to load resolver "alias".](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +`;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/components/ModalsManager.js
> +import ShowScreenShot from "../modals/ShowScreenShot";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Missing file extension for "../modals/ShowScreenShot"](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/utils/constants.js
> +export const CLIENT_ID = "18d87e44184ea34";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import Modal from "../components/Modal";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import styled from "styled-components";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  console.log(ScreenShotsDir, file.name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-02 21:10 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  const image = path.join(ScreenShotsDir, file.name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 25
           

Clones added
============
- src/common/modals/InstanceManager/Notes.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094&bid=16716777)

2020-03-03 12:47 UTC, killpowa commented on src/common/components/ModalsManager.js
> +import ShowScreenShot from "../modals/ShowScreenShot";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +`;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented on src/common/components/ModalsManager.js
> +import ShowScreenShot from "../modals/ShowScreenShot";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Missing file extension for "../modals/ShowScreenShot"](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented on src/common/api.js
> +  });
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented on src/common/utils/constants.js
> +export const CLIENT_ID = "18d87e44184ea34";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:47 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import Modal from "../components/Modal";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  console.log(ScreenShotsDir, file.name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/api.js
> +  return res;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/api.js
> +  const bodyFormData = new FormData();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import React from "react";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Resolve error: unable to load resolver "alias".](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import styled from "styled-components";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  const image = path.join(ScreenShotsDir, file.name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import React from "react";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import Modal from "../components/Modal";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Missing file extension for "../components/Modal"](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +import path from "path";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/modals/ShowScreenShot.js
> +  );
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-03 12:48 UTC, killpowa commented on src/common/api.js
> +  bodyFormData.append("image", image);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Delete `;`](https://app.codacy.com/manual/gorilla-devs/GDLauncher/pullRequest?prid=5082094)

2020-03-08 18:31 UTC, blarfoon requested changes

2020-03-08 18:31 UTC, killpowa commented on src/common/components/ModalsManager.js
> +import ConfirmationModal from "../modals/ConfirmationModal";
No other modal has the `modal` name in it. Follow conventions. Call it `ActionConfirmation`

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/ConfirmationModal.js
> +const applyChoise = async (
`applyChoice`

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/ConfirmationModal.js
> +  abortCallback,
Confirm and abort callback should be one next to the other

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/ConfirmationModal.js
> +      title="Confirm"
It should be possible to customize the title

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +          <NoScreenAvailable>No ScreensShots Available</NoScreenAvailable>
`No Screenshots Available`

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  height: 100px;
Height is set 2 times

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  width; 10px;
Does this even work?

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  z-index: 1000;
Why 1000? Why not just 2

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  padding: 0 !important;
Why important?

2020-03-08 18:31 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  height: 100px;
Height is set 2 times

2020-03-08 19:22 UTC, blarfoon requested changes

2020-03-08 19:22 UTC, killpowa commented on src/common/modals/InstanceManager/Screenshots.js
> +  padding: 0 ;
Remove whitespace

2020-03-08 19:30 UTC, merged