different  sysNavbar for osx and win
gorilla-devs/GDLauncher pull request #356
Opened 2020-03-24 21:41 UTC by Ladvace

2020-03-25 13:06 UTC, blarfoon requested changes

2020-03-25 13:06 UTC, killpowa commented on src/app/desktop/components/SystemNavbar.js
>      width: 35px;
Too much duplicated code here. Please extract the logic and reduce code complexity

2020-03-25 13:06 UTC, killpowa commented on src/app/desktop/components/SystemNavbar.js
> +const osx = process.platform === 'darwin';
Variable should be called `isOsx` since it's a condition

2020-03-25 13:06 UTC, killpowa commented on public/electron.js
> +  console.log('CIAO');
Remove useless console log

2020-03-25 13:06 UTC, killpowa commented on public/electron.js
> +ipcMain.handle('open-devTools', () => {
This should all be lowercase

2020-03-25 13:06 UTC, killpowa commented on src/app/desktop/components/SystemNavbar.js
> +    ipcRenderer.invoke('open-devTools');
This should all be lowercase

2020-03-25 14:01 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/components/SystemNavbar.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5243673&bid=17187152)

2020-03-25 14:20 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/components/SystemNavbar.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5243673&bid=17187152)

2020-03-26 01:47 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/components/SystemNavbar.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5243673&bid=17187152)

2020-03-26 19:33 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/components/SystemNavbar.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5243673&bid=17187152)

2020-03-26 20:59 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/components/SystemNavbar.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5243673&bid=17187152)

2020-03-26 21:11 UTC, merged