new onBoarding Modal
gorilla-devs/GDLauncher pull request #388
Opened 2020-04-08 13:59 UTC by Ladvace

2020-04-08 14:02 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/Onboarding/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5328128&bid=17439995)

2020-04-10 00:54 UTC, blarfoon requested changes

2020-04-10 00:54 UTC, killpowa commented on src/app/desktop/views/Home.js
> +    console.log('NEW', isNewUser);
Remove

2020-04-10 00:54 UTC, killpowa commented on src/app/desktop/views/Home.js
> +    console.log('K', isNewUser);
Remove

2020-04-10 00:54 UTC, killpowa commented on src/app/desktop/views/Home.js
> +      openWelcomePage();
It's a modal not a page

2020-04-10 00:54 UTC, killpowa commented on src/common/modals/Onboarding/index.js
> +                    console.log('pippo ', page + i);
Pippo

2020-04-10 00:54 UTC, killpowa commented on src/common/modals/Onboarding/index.js
> +                  console.log('£££', i, page);
...

2020-04-10 00:54 UTC, killpowa commented on src/common/reducers/actions.js
> -        dispatch(push('/onboarding'));
If it's a new user they won't be redirected anwhere

2020-04-10 00:54 UTC, killpowa commented on src/common/reducers/actions.js
> -          dispatch(push('/onboarding'));
If it's a new user they won't be redirected anwhere

2020-04-10 00:54 UTC, killpowa commented on yarn.lock
> -debug@^3.0.0, debug@^3.1.1, debug@^3.2.5, debug@^3.2.6:
Why change the yarn lock?

2020-04-10 00:54 UTC, killpowa commented on src/common/modals/Onboarding/index.js
> +  padding-top: calc(${props => props.theme.sizes.height.systemNavbar} + 5px);
This doesn't look solid. Why `props.theme.sizes.height.systemNavbar} + 5px`?

2020-04-10 00:54 UTC, killpowa commented on src/common/modals/Onboarding/index.js
> +  const [currentSlide, setCurrentSlide] = useState(0);
What's the difference between page and currentSlide?

2020-04-10 19:50 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/Onboarding/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5328128&bid=17439995)

2020-04-13 20:23 UTC, blarfoon requested changes

2020-04-13 20:23 UTC, killpowa commented on src/common/reducers/actions.js
>        }
Onboarding doesn't exist anymore, this will fail

2020-04-13 20:23 UTC, killpowa commented on src/common/reducers/actions.js
> +        dispatch(push('/onboarding'));
Same as above

2020-04-28 18:16 UTC, blarfoon requested changes
Pr is not complete. There are still references to `/onboarding` and there are some blank redirects

2020-04-28 18:16 UTC, killpowa commented on src/app/desktop/views/Home.js
> +
What's the point of this function? It's used in only 1 place and it does only one thing

2020-04-28 18:16 UTC, killpowa commented on src/common/modals/Onboarding/index.js
> +                  } else executeScroll(i - page);
??

2020-04-28 18:16 UTC, killpowa commented on src/app/desktop/views/Home.js
> +    }
This should not be here. This should be called from the action

2020-04-29 11:08 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/Onboarding/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5328128&bid=17439995)

2020-04-30 08:29 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/Onboarding/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5328128&bid=17439995)

2020-04-30 09:35 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/app/desktop/views/Onboarding.js  4
- src/common/modals/Onboarding/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5328128&bid=17439995)

2020-05-05 13:39 UTC, closed without merging