Removed some Dom errors
gorilla-devs/GDLauncher pull request #450
Opened 2020-05-06 04:57 UTC by TOLoneWolf

Removed some Dom errors:
- active
- selectedMods
- selectedItems

Based on:
<https://github.com/styled-components/styled-components/issues/1198#issuecomment-425650423>

2020-05-06 11:55 UTC, blarfoon requested changes

2020-05-06 11:55 UTC, killpowa commented on src/common/modals/InstanceManager/Mods.js
> +            selectedMods={(selectedMods.length > 0).toString()}
Please don't do this. It's enough to remove the key from the dom element

2020-05-06 11:55 UTC, killpowa commented on src/common/modals/InstanceManager/Notes.js
> +      active={isBlockActive(editor, format).toString()}
Same here, you should keep it as boolean but not passing it to the dom element

2020-05-06 14:35 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/common/modals/InstanceManager/Notes.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5477610&bid=17952050)

2020-05-09 13:03 UTC, blarfoon requested changes

2020-05-09 13:03 UTC, killpowa commented on src/common/modals/InstanceManager/Notes.js
> +      active={isBlockActive(editor, format).toString()}
Same here, remove toString and just strip this down from the props

2020-05-09 14:23 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/common/modals/InstanceManager/Notes.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5477610&bid=17952050)

2020-05-09 14:48 UTC, killpowa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/common/modals/InstanceManager/Notes.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5477610&bid=17952050)

2020-05-09 19:38 UTC, merged