Implement Better Dynamic Slider
gorilla-devs/GDLauncher pull request #971
Opened 2021-06-28 01:12 UTC by meponderR

## Purpose
This changes the RAM slider to change depending on the amount of RAM the user has in their PC. With this change the Slider will go up to 4GB if the user has 4GB; 64 if the user has 64GB; etc. This is not hardcoded as opposed to #957 as requested by @killpowa in https://github.com/gorilla-devs/GDLauncher/issues/957#issuecomment-868727103. The original PR did not go through as the pull bot force pushed my branch.

## Approach
This uses a counter to cycle through 2048, 4096, 8192, 16384, etc

2021-07-25 14:29 UTC, blackcat-917 commented
Addressed in `3a93317`

2021-07-25 14:32 UTC, meponderR commented
> This was addressed in [3a93317](https://github.com/gorilla-devs/GDLauncher/commit/3a93317087790ae86a30b528fec15c7ceb8d6e91)

This also adds a much better marking system than #957.

2021-08-06 09:33 UTC, Code-Ac commented
> > This was addressed in [3a93317](https://github.com/gorilla-devs/GDLauncher/commit/3a93317087790ae86a30b528fec15c7ceb8d6e91)
> 
> This also adds a much better marking system than #957.

No, it just sets a mark for every full mark on the function x^2 and causes more non-needed cpu usage. We can do what you did simply by adding more marks on the slider.

2021-08-06 09:39 UTC, meponderR commented
> No, it just sets a mark for every full mark on the function x^2 and causes more non-needed cpu usage. We can do what you did simply by adding more marks on the slider.

It was requested by killpowa as stated in the original comment. 

> This is not hardcoded as opposed to #957 as requested by @killpowa in [#957 (comment)](https://github.com/gorilla-devs/GDLauncher/pull/957#issuecomment-868727103)

Also, the cpu usage is still very low.

2021-08-06 10:37 UTC, Code-Ac commented
Yes, you’re right. But it still has to cycle through every `**` operation.
Whit too much hardcoding he is right but my point is: you just don’t need this function (btw the math behind it is great!)

2021-08-06 12:06 UTC, Code-Ac commented
Just look at my pr to fix this: #967
There was only one line to be changed and it works exactly the same way it does whit your version

2021-08-06 20:19 UTC, meponderR commented
> Just look at my pr to fix this: #967
> There was only one line to be changed and it works exactly the same way it does whit your version
> Edit: I know 1000 is the wrong number, fix is also merged

The only point of this is if someone has 64, 128, 256, etc. gibibytes of ram and wants marks for the previous powers of 2.

2021-08-06 20:57 UTC, Code-Ac commented
If you really think someone needs markers that high, just add them lol

2021-08-14 22:03 UTC, killpowa requested changes
This PR is good but there is still an issue with the number of marks. 
![image](https://user-images.githubusercontent.com/10165264/129461020-56c5a2fd-c598-48c0-85c3-00f6d6af27b2.png).

I think a solution for this would be to count the vicinity of 2 marks and only add them to the marks array if they are far enough from each other.
Assuming we show marks for every power of 2GB
Let's say I have 8GB of RAM, that means marks will be 2, 4, 8GB. 
2-8 is 100% of the distance and 2-4 is 50% of it, we will show all of them.
Now let's say I have 32GB of RAM, that means we have marks for 2, 4, 8, 16, 32GB.
Now 2-32 is 100% of the distance but 2-4 is only 1/16th or around 6% of it. This is too low of a value and the text will overlap so we will not show it. I don't know the exact threshold but you can make a few tries. If you can address this change I will merge it!

2021-08-14 22:03 UTC, blarfoon commented on src/common/modals/Settings/components/Java.js
> +          openJDK shipped with GDLauncher. Please select the java.exe binary
This won't work for linux/macOS

2021-08-14 22:03 UTC, blarfoon commented on src/common/modals/Settings/components/Java.js
> +  for (let b2Counter = b2TotalMemory; b2Counter > 0; b2Counter -= 1) {
Is it really necessary to go over every single number from `Math.log2(totalMemory)` to 0?
Looks like a lot of unnecessary loop steps, am I missing something?

2021-08-14 22:03 UTC, blarfoon commented on src/common/modals/Settings/components/Java.js
> +function getMarks() {
This should eventually be extracted to an util function and imported into the 2 files

2021-12-29 15:03 UTC, LilyRose2798 commented
Just an FYI for anyone looking at this PR, I have an open PR #1227 which addresses the issue mentioned here in a different way (rather than keeping a linear scale and changing where marks are placed, the scale is changed to be logarithmic so that all power of two GBs up to the user's memory can be displayed equally spaced without overlaps).

2022-06-19 18:40 UTC, closed without merging